module.exports = {
  points: {
    upload: "UPLOAD",
    auth: "AUTH",
    users: "USERS",
    roles: "ROLES",
    user_roles: "USER_ROLES",
    user_permissions: "USER_PERMISSIONS",
    audit_logs: "AUDIT_LOGS",
    firma: "FIRMA",
    sube: "SUBE",
    pozisyon: "POZISYON",
    firmaPersonel: "FIRMA_PERSONEL",
  },
  types: {
    get: "GET",
    list: "LIST",
    create: "CREATE",
    update: "UPDATE",
    delete: "DELETE",
    report: "REPORT",
    print: "PRINT",
    import: "IMPORT",
    export: "EXPORT",
    upload: "UPLOAD",
    login: "LOGIN",
    logout: "LOGOUT",
    register: "REGISTER",
  },
};
